name: Build and deploy Adonis app to Azure Web App

env:
  AZURE_WEBAPP_NAME: adonisbackend
  AZURE_WEBAPP_PACKAGE_PATH: '${{ github.workspace }}/myapp'

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Prepare package
        run: |
          mkdir -p ${{ github.workspace }}/myapp
          cp -r . ${{ github.workspace }}/myapp
          cp -r ./database ${{ github.workspace }}/myapp/database

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ${{ github.workspace }}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: List directory contents
        run: ls -la ${{ github.workspace }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/myapp
