name: Build and deploy Adonis app to Azure Web App

env:
  AZURE_WEBAPP_NAME: backendimoveis
  AZURE_WEBAPP_PACKAGE_PATH: '${{ github.workspace }}/myapp'

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Set environment variables
        run: |
          echo PORT=${{ secrets.PORT }} >> .env
          echo HOST=${{ secrets.HOST }} >> .env
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env
          echo APP_KEY=${{ secrets.APP_KEY }} >> .env
          echo DRIVE_DISK=${{ secrets.DRIVE_DISK }} >> .env
          echo DB_CONNECTION=${{ secrets.DB_CONNECTION }} >> .env
          echo DB_FILEPATH=${{ secrets.DB_FILEPATH }} >> .env
          echo NUCLEO_LEILOES_API_URL=${{ secrets.NUCLEO_LEILOES_API_URL }} >> .env
          echo VIVA_REAL_API_URL=${{ secrets.VIVA_REAL_API_URL }} >> .env
          echo VIVA_REAL_SITE_URL=${{ secrets.VIVA_REAL_SITE_URL }} >> .env

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --production -- --ignore-ts-errors

      - name: Prepare package
        run: |
          mkdir -p ${{ github.workspace }}/myapp
          cp -r ./app ${{ github.workspace }}/myapp/app
          cp -r ./database ${{ github.workspace }}/myapp/database
          cp -r ./public ${{ github.workspace }}/myapp/public
          cp -r ./resources ${{ github.workspace }}/myapp/resources
          cp -r ./start ${{ github.workspace }}/myapp/start
          cp -r ./config ${{ github.workspace }}/myapp/config
          cp -r ./build ${{ github.workspace }}/myapp/build
          cp .env ace-manifest.json package.json package-lock.json ${{ github.workspace }}/myapp/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ${{ github.workspace }}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: List directory contents
        run: ls -la ${{ github.workspace }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/myapp
