name: Build and deploy Adonis app to Azure Web App

env:
  AZURE_WEBAPP_NAME: backendimoveis
  AZURE_WEBAPP_PACKAGE_PATH: 'myapp'
  NODE_VERSION: '18.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build --production -- --ignore-ts-errors

      - name: Set environment variables
        run: |
          echo PORT=${{ secrets.PORT }} >> .env
          echo HOST=${{ secrets.HOST }} >> .env
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env
          echo APP_KEY=${{ secrets.APP_KEY }} >> .env
          echo DRIVE_DISK=${{ secrets.DRIVE_DISK }} >> .env
          echo DB_CONNECTION=${{ secrets.DB_CONNECTION }} >> .env
          echo DB_FILEPATH=${{ secrets.DB_FILEPATH }} >> .env
          echo NUCLEO_LEILOES_API_URL=${{ secrets.NUCLEO_LEILOES_API_URL }} >> .env
          echo VIVA_REAL_API_URL=${{ secrets.VIVA_REAL_API_URL }} >> .env
          echo VIVA_REAL_SITE_URL=${{ secrets.VIVA_REAL_SITE_URL }} >> .env

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
