name: Build and deploy Adonis app to Azure Web App

env:
  AZURE_WEBAPP_NAME: backendimoveis
  AZURE_WEBAPP_PACKAGE_PATH: '${{ github.workspace }}/myapp'

on:
  push:
    branches: ['main', 'staging', 'development']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}/backend-imoveis
        run: |
          docker build -t $IMAGE_NAME:${{ github.ref_name }} .
          docker push $IMAGE_NAME:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Azure
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}/backend-imoveis
          AZURE_WEBAPP_NAME: backendimoveis
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_SSH_USER }}@${{ secrets.AZURE_SSH_HOST }} << 'EOF'
          docker pull $IMAGE_NAME:${{ github.ref_name }}
          docker stop $AZURE_WEBAPP_NAME || true
          docker rm $AZURE_WEBAPP_NAME || true
          docker run -d --name $AZURE_WEBAPP_NAME -p 80:3333 $IMAGE_NAME:${{ github.ref_name }}
          docker system prune -af
          EOF
